### ISSUE TITLE
[BUG] Passing a model file in inochi-session binary opens the model but the same doesn't work in the AppImage

### ISSUE THREAD

**Issue by sanket143** [Inochi2D/inochi-session#17]
### Validations

- [X] I have checked for similar bug reports and could not find any.
- [X] I have tested and confirmed that this is an issue in an official branded build.

### Describe the bug

I am trying to open a inx model in inochi-session using the following
```
$ inochi-session-x86_64.AppImage ./models/Midori.inx
```
but it's still opening an empty inochi-session

I think adding "$@" in the AppRun may help solving the issue.

ref: https://discourse.appimage.org/t/command-line-parameter-transfer/1537

### Reproduction

1. Download AppImage build and example models from https://github.com/Inochi2D/inochi-session/releases/tag/v0.5.4 and make the AppImage executable
2. Run `$ inochi-session-x86_64.AppImage ./path/to/Midori.inx`, is expected to open inochi-session with "Midori" model but is opening empty session

### System Architecture

x86_64

### Operating System

Linux

### Version

v0.5.4

**Comment by LunaTheFoxgirl** [comment]
This issue has already been solved by https://github.com/Inochi2D/inochi-session/pull/12, you may use nightly builds for now to solve your issue until I release the next version
