### ISSUE TITLE
[Feature Request] Add 'File' menu for opening models

### ISSUE THREAD

**Issue by helloar14** [Inochi2D/inochi-session#26]
### Validations

- [X] I have checked for similar feature requests and could not find any.
- [X] I have made sure this is not an already-existing feature.

### Description

Drag-and-dropping model file from file manager doesn't come naturally for a lot of users, so a clear and obvious File->Open menu will help a lot.

### Suggested solution

Add 'File' menu with 'Open' function to the existing top menu.

**Comment by orowith2os** [comment]
I had https://github.com/Inochi2D/inochi-session/pull/15 but it might be better to implement the GUI bit for it first and then worry about the system part.
