### ISSUE TITLE
[BUG] Segfault with empty zone

### ISSUE THREAD

**Issue by prettykool** [Inochi2D/inochi-session#30]
### Validations

- [X] I have checked for similar bug reports and could not find any.
- [X] I have tested and confirmed that this is an issue in an official branded build.

### Describe the bug

When trying to run this software using integrated graphics on an AMD CPU, it segfaults (`SIGSEGV`) when trying to launch. The hardware in question is `AMD Ryzen 7 4700U with Radeon Graphics`, per `lscpu`

### Reproduction

See description.

### System Architecture

x86_64

### Operating System

Linux

### Version

Nightly (As of 19:11, UTC-5, April 23)

### Logs

<details>
<summary>Click to expand!</summary>
```
$ ./inochi-session
[INFO] Inochi Session commit+610ccc8, args=[]
[INFO] Lua support initialized. (Statically linked for now)
[INFO] Scanning plugins at /home/pk/.config/inochi-session/plugins...
[ERR ] Could not start texture sharing, it will be disabled. Is the library missing?
Segmentation fault (core dumped)
$
```
</details>

**Comment by prettykool** [comment]
Luna suggested using `gdb` to check the value of `bt`, so here goes:
```
(gdb) bt
#0  0x00005555555a47a2 in _D7session8tracking6vspace12VirtualSpace19isCurrentZoneActiveMFZb (this=0x7ffff7b82720) at source/session/tracking/vspace.d:180
#1  0x000055555559fc16 in _D7session5scene14insUpdateSceneFZv () at source/session/scene/package.d:267
#2  0x000055555559f281 in _D7session7windows4main19InochiSessionWindow13onEarlyUpdateMFZv (this=0x7ffff7b7e380) at source/session/windows/main.d:56
#3  0x00005555556687ff in _D4inui4core6window6appwin19InApplicationWindow6updateMFZv (this=0x7ffff7b7e380) at inui/source/inui/core/window/appwin.d:370
#4  0x00005555555c047b in _Dmain (args=...) at source/app.d:52
```

**Comment by LunaTheFoxgirl** [comment]
Fixed by https://github.com/Inochi2D/inochi-session/commit/aaaa22166e18cee5fc1355ef1b1a3c2de337f857
